### ISSUE TITLE
EventGroupProcessor does only execute the first registered handler for each event type

### ISSUE THREAD

**Issue by Darkskald** [ThreeDotsLabs/watermill#402]
When running the example [basic/5-cqrs-protobuf](https://github.com/ThreeDotsLabs/watermill/tree/master/_examples/basic/5-cqrs-protobuf), using the group handlers  (`watermill v1.3.5`, `watermill-amqp/v2 v2.1.0`)

```golang
	err = eventProcessor.AddHandlersGroup(
		"events",
		OrderBeerOnRoomBooked{commandBus},
		NewBookingsFinancialReport(),

		cqrs.NewGroupEventHandler(func(ctx context.Context, event *BeerOrdered) error {
			logger.Info("Beer ordered", watermill.LogFields{
				"room_id": event.RoomId,
			})
			return nil
		}),
	)
```
only the first handler for the RoomBooked event (OrderBeerOnRoomBooked) is executed, the output of the other handler is never visible. Upon interchanging them:

```golang
		NewBookingsFinancialReport(),
		OrderBeerOnRoomBooked{commandBus},
```

only the message from NewBookingsFinancialReport is displayed. From this observation I deduce that in the current implementation of EventGroupProcessors **executes only the first handler** for a specific event type and ignores all others.

**Comment by Darkskald** [comment]
I created a [PR](https://github.com/ThreeDotsLabs/watermill/pull/403) that should solve that issue, unfortunately I confused 403 and 402... sorry for that!

**Comment by MagdielCAS** [comment]
Any updates regarding this? 6 months later and it is still an issue, I spent some hours trying to figuring out why my code didn't work when it actually was the lib that returned after the first execution

**Comment by germainc** [comment]
Agree this would be a good change. The only workaround seems to be multiple handler groups but that can create a huge mess. If you have a domain with 10 events and need a second handler for 1 of them, you now have a group with 9 extra handlers returning `nil` just to ack messages. You can turn on `AckOnUnknownEvent` but that's a terrible idea since you have to turn it on for the entire processor.

**Comment by ilusharulkov** [comment]
Hello, Any updates regarding this?

**Comment by desprit** [comment]
So yeah, this handler never gets executed:
https://github.com/ThreeDotsLabs/watermill/blob/master/_examples/basic/5-cqrs-protobuf/main.go#L296
the one above it runs first and consumes `RoomBooked` event

thought it was something wrong on my side but figured there's a ticket already

can we get some feedback here, please?

**Comment by roblaszczak** [comment]
Fix for that is on main: https://github.com/ThreeDotsLabs/watermill/commit/9d5e2da133397fcfb6e8f00eb424df91005e9c7a

But please remember that we don't recommend using group handlers this way ⚠️ If you have two handlers for the same event within a group, and the second one fails, the second one will be executed again. I assume you should be prepared for re-delivery, but it may be a better idea not to put them in the same group if possible.

After discussing it with @m110, we also decided that the current examples are a bit misleading (including the fact that they were not fully correct).

To address it, I modified the 5-cqrs-protobuf example to not use groups (because we don't need order in this example really) and created a more specific 6th example that uses this mechanism together with message ordering: https://github.com/ThreeDotsLabs/watermill/pull/525
